version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: edgr-nginx
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles
    depends_on:
      - django-web
    dns:
      - 8.8.8.8
      - 8.8.4.4
    deploy:
      resources:
        limits:
          memory: "256m"

  django-web:
    build:
      context: .
      dockerfile: Dockerfile.local  # Or Dockerfile if you don’t split prod/local
    platform: linux/amd64
    container_name: edgr-django-web
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=edgr_invest.settings.base
    ports:
      - "8001:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles
      - .:/app
    env_file:
      - .env
    shm_size: '2gb'
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 edgr_invest.wsgi:application"
    depends_on:
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:latest
    container_name: edgr-redis
    restart: always
    volumes:
      - redis-data:/data
    dns:
      - 8.8.8.8
      - 8.8.4.4
    deploy:
      resources:
        limits:
          memory: "256m"

volumes:
  redis-data:
