# Generated by Django 4.2.3 on 2025-04-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initial_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
