# Generated by Django 4.2.3 on 2025-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_waitlistsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('quarter', models.CharField(max_length=6)),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dividend_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dividend_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rollover_paid', models.CharField(choices=[('rollover', 'Rollover'), ('paid', 'Paid')], default='rollover', max_length=10)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'investment_summary',
                'ordering': ['-quarter'],
            },
        ),
    ]
