# Generated by Django 4.2.3 on 2025-04-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_investmentsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsummary',
            name='dividend_paid',
            field=models.BooleanField(default=False),
        ),
    ]
