# Generated by Django 4.2.3 on 2025-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_investmentsummary_rollover_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSummaryDeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('quarter', models.CharField(max_length=6)),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dividend_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dividend_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unrealized_gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rollover_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dividend_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'investment_summary_deux',
                'ordering': ['-quarter'],
            },
        ),
    ]
