# Generated by Django 4.2.3 on 2025-05-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_investmentsummarydeux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentsummarydeux',
            name='rollover_paid',
        ),
    ]
