# Generated by Django 4.2.3 on 2025-07-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_investmentsummarydeux_rollover_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentsummarydeux',
            options={'ordering': ['-month']},
        ),
        migrations.RenameField(
            model_name='investmentsummarydeux',
            old_name='ending_balance',
            new_name='current_balance',
        ),
        migrations.RemoveField(
            model_name='investmentsummarydeux',
            name='quarter',
        ),
        migrations.AddField(
            model_name='investmentsummarydeux',
            name='month',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
