# Generated by Django 4.2.3 on 2025-07-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_investmentsummarydeux_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentsummarydeux',
            options={'ordering': ['-quarter']},
        ),
        migrations.RenameField(
            model_name='investmentsummarydeux',
            old_name='month',
            new_name='quarter',
        ),
    ]
