# Generated by Django 4.2.3 on 2025-07-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_investmentsummarydeux_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentsummarydeux',
            old_name='current_balance',
            new_name='ending_balance',
        ),
        migrations.AlterField(
            model_name='investmentsummarydeux',
            name='quarter',
            field=models.CharField(max_length=6),
        ),
    ]
