# Generated by Django 4.2.3 on 2025-07-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_current_balance_investmentsummarydeux_ending_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentsummarydeux',
            name='quarter',
            field=models.CharField(max_length=15),
        ),
    ]
