# Generated by Django 4.2.3 on 2025-07-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_investmentsummarydeux_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='quarter',
        ),
    ]
