# Generated by Django 4.2.3 on 2025-07-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_investment_current_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investment',
            name='quarter',
            field=models.CharField(default='Q1-25', max_length=6),
        ),
    ]
